### PR TITLE
[TASK] Add compatibility to TYPO 7.4

### PR DESCRIPTION
**Pull request by IchHabRecht**

### CODE REVIEW

**Comment by adgrafik** [comment]
Hi!
Thanks for support this extension! Currently I haven't much time for merge, but for what are the methods `countFilesInFolder`, `countFoldersInFolder` and `getFileInFolder`? Dou you need them? I can't find them in `AbstractHierarchicalFilesystemDriver` in the current branches of 7.4 neither in master.

**Comment by IchHabRecht** [comment]
Hi. You can find the extension of the driver in typo3/sysext/core/Classes/Resource/Driver/DriverInterface.php

**Comment by adgrafik** [comment]
Witch version? Not in 7.4:
- https://git.typo3.org/Packages/TYPO3.CMS.git/blob/c3ae8d677d59439777121b32548004ef4a8838ea:/typo3/sysext/core/Classes/Resource/Driver/AbstractDriver.php
- https://git.typo3.org/Packages/TYPO3.CMS.git/blob/c3ae8d677d59439777121b32548004ef4a8838ea:/typo3/sysext/core/Classes/Resource/Driver/AbstractHierarchicalFilesystemDriver.php

**Comment by IchHabRecht** [comment]
Sure in current versions. See right file https://git.typo3.org/Packages/TYPO3.CMS.git/blob/c3ae8d677d59439777121b32548004ef4a8838ea:/typo3/sysext/core/Classes/Resource/Driver/DriverInterface.php

**Comment by adgrafik** [comment]
Interface! OK, du hast eben immer Recht :)

**Comment by adgrafik** [comment]
Merged in v1.3.0.
Thanks for support!

**Pull request closed without merging**
